# Generated by Django 5.1.4 on 2026-09-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('order_id', models.CharField(max_length=64)),
                ('number', models.CharField(max_length=32)),
                ('amount_paise', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'demo_invoice',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('order_id', models.CharField(max_length=64)),
                ('channel', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'demo_notification',
            },
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('order_id', models.CharField(max_length=64)),
                ('sku', models.CharField(max_length=64)),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'demo_stock_reservation',
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('order_id', models.CharField(max_length=64)),
                ('amount_paise', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'demo_charge',
                'indexes': [models.Index(fields=['order_id'], name='demo_charge_order_i_b63764_idx')],
            },
        ),
        migrations.CreateModel(
            name='GatewayCall',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('order_id', models.CharField(max_length=64)),
                ('amount_paise', models.BigIntegerField()),
                ('deduped', models.BooleanField(default=False)),
                ('failed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'demo_gateway_call',
                'indexes': [models.Index(fields=['order_id'], name='demo_gatewa_order_i_4713a7_idx')],
            },
        ),
    ]
