# Generated by Django 5.1.4 on 2026-09-24 06:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('hostname', models.CharField(blank=True, default='', max_length=200)),
                ('pid', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('claimed', models.IntegerField(default=0)),
                ('succeeded', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('current_step', models.CharField(blank=True, default='', max_length=128)),
            ],
            options={
                'db_table': 'keel_worker',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow', models.CharField(max_length=128)),
                ('idempotency_key', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('input', models.JSONField(default=dict)),
                ('context', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'keel_workflow_run',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['state', '-created_at'], name='keel_workfl_state_1c1b8f_idx'), models.Index(fields=['workflow', '-created_at'], name='keel_workfl_workflo_86cff1_idx')],
            },
        ),
        migrations.CreateModel(
            name='StepRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('seq', models.IntegerField()),
                ('state', models.CharField(choices=[('blocked', 'Blocked'), ('ready', 'Ready'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('dead', 'Dead'), ('cancelled', 'Cancelled')], default='blocked', max_length=16)),
                ('attempt', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('reclaimed', models.IntegerField(default=0)),
                ('run_after', models.DateTimeField()),
                ('lease_owner', models.CharField(blank=True, max_length=128, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('output', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('error_type', models.CharField(blank=True, default='', max_length=128)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='engine.workflowrun')),
            ],
            options={
                'db_table': 'keel_step_run',
                'ordering': ['seq'],
            },
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('step_name', models.CharField(blank=True, default='', max_length=128)),
                ('topic', models.CharField(max_length=128)),
                ('payload', models.JSONField(default=dict)),
                ('dedupe_key', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('publish_attempts', models.IntegerField(default=0)),
                ('publish_after', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('lease_owner', models.CharField(blank=True, max_length=128, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='engine.workflowrun')),
            ],
            options={
                'db_table': 'keel_outbox_event',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idempotency', to='engine.workflowrun')),
            ],
            options={
                'db_table': 'keel_idempotency_record',
            },
        ),
        migrations.CreateModel(
            name='DeadLetter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('workflow', models.CharField(max_length=128)),
                ('step_name', models.CharField(max_length=128)),
                ('attempts', models.IntegerField()),
                ('error', models.TextField(blank=True, default='')),
                ('error_type', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('replayed_at', models.DateTimeField(blank=True, null=True)),
                ('replay_count', models.IntegerField(default=0)),
                ('step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dead_letter', to='engine.steprun')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dead_letters', to='engine.workflowrun')),
            ],
            options={
                'db_table': 'keel_dead_letter',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='steprun',
            index=models.Index(fields=['state', 'run_after'], name='keel_step_claim_idx'),
        ),
        migrations.AddIndex(
            model_name='steprun',
            index=models.Index(fields=['state', 'lease_expires_at'], name='keel_step_lease_idx'),
        ),
        migrations.AddIndex(
            model_name='steprun',
            index=models.Index(fields=['run', 'seq'], name='keel_step_run_seq_idx'),
        ),
        migrations.AddConstraint(
            model_name='steprun',
            constraint=models.UniqueConstraint(fields=('run', 'name'), name='keel_step_unique_per_run'),
        ),
        migrations.AddIndex(
            model_name='outboxevent',
            index=models.Index(condition=models.Q(('published_at__isnull', True)), fields=['publish_after'], name='keel_outbox_pending_idx'),
        ),
        migrations.AddIndex(
            model_name='outboxevent',
            index=models.Index(fields=['run', 'id'], name='keel_outbox_run_idx'),
        ),
        migrations.AddIndex(
            model_name='deadletter',
            index=models.Index(fields=['replayed_at', '-created_at'], name='keel_dlq_idx'),
        ),
    ]
