# Generated by Django 5.1.4 on 2026-09-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='steprun',
            name='effects_performed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='steprun',
            name='effects_replayed',
            field=models.IntegerField(default=0),
        ),
    ]
